channels:
  - conda-forge
dependencies:
  - matplotlib=3.8.4
  - numpy=1.24.4
  - pandas=2.2.2
  - pip=24.0
  - python=3.11.9
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - statsmodels=0.14.1
  - pyinstaller=6.7.0
  - pip:
      - brain-isotopic-distribution==1.5.16
      - linear-tree==0.3.5
      - gdown
