#All paths and files in this document should be relative to working_directory
#working_directory should be an absolute path
working_directory = '/home/4vt/Documents/data/SLT05_MSDpostprocess/MSDpostprocess/example_data'
data = ['training_data.tsv']
#seed value for the rng used in train-test spliting
seed = 1
#analytes eluting before this time (in minutes) will be categorized as not_considered
min_rt = 7
#fraction of dat used for the lowess regression based RT correction
#increase this value if the RT regression plot seems excessively sensitive to noise
#reduce this value if RT regression fails to fit real features of the data
lowess_frac = 0.15
#whether calculated m/z error should be in units of ppm. If false units are Da.
ppm = false
#persistant model file
model = 'test_model'
#if true a preexisting model and outputs will be overwritten
overwrite = true
#cores = 8
#should be one of 'train' or 'infer'
mode = 'train'
#fraction of provided data used for training
#validation will be carried out on the remaning fraction
#parameter ignored for inference
test_split = 0.8
#directory to save outputs. Will be created if not extant
output = 'test'

[cutoffs]
mz_correction = 0.5
rt_correction = 0.5
#below the first element predictions are classed negative
#above the second they're classed positive
#in between they're classed needs_reanalysis
predictor_model = [0.3,0.8]

[features]
mz_correction = ['Dot product', 'S/N average', 'isotope_error']
rt_correction = ['Dot product', 'S/N average', 'isotope_error', 'mz_error']
predictor_model = ['Dot product', 'S/N average', 'isotope_error', 'mz_error', 'rt_error']
